import { GlobalContextProvider } from '@/components/Provider'
import './globals.css'
import type { Metadata } from 'next'

import { Inter } from 'next/font/google'
// import {  UserProvider } from '@/components/context/UserContext'
import { ContextContainer } from './context-container'
// import { dehydrate, QueryClient } from "@tanstack/query-core";
import { getUsers } from '@/lib/queries/getUsers'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import ReactQueryProvider from '@/components/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>

          {/* <ContextContainer state={state}>
        {children}
          <ReactQueryDevtools initialIsOpen={false} />
        </ContextContainer> */}
          {/* <UserProvider> */}
          {/* <GlobalContextProvider> */}
          {children}
          <ReactQueryDevtools initialIsOpen={false} />

          {/* </GlobalContextProvider> */}
          {/* </UserProvider> */}
        </ReactQueryProvider>
      </body>
    </html>
  )
}
